### ISSUE TITLE
[FEA] Add support for passing gpu architecture(s) to be compiled against

### ISSUE THREAD

**Issue by teju85** [rapidsai/nvgraph#4]
We need this in cuML, as we'd like to pass the `GPU_ARCHS` that the user has passed to cuml cmake command to nvgraph during its build. Currently, it seems that nvgraph cmakelists file hardcodes it to `sm_60` and `sm_70`.

**Comment by afender** [comment]
It seems `sm_75` was the missing one : b2a9f11

**Comment by teju85** [comment]
@afender Not just that. I'd like to pass architectures explicitly during cmake commandline. For eg: in case I wanted to *only* build for "70", I'd like to do so by passing something like: `cmake -DGPU_ARCHS=70 ..`
